services:
  walkman-server:
    image: ghcr.io/djmanri3/walkman-server:main
    env_file:
      - .env
    #environment:
      # Edit this default values if do you want ;)
      #DEFAULT_LANGUAGE: English
      #DEFAULT_SERVER_TYPE: Emby
      #DEFAULT_SERVER_URL: "http://127.0.0.1:8096"
    ports:
      - 8081:80
